name: 'test_dbt_snowflake'
version: '1.0.0'

profile: 'test_dbt_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order: ['test_dbt_snowflake', 'dbt']

models:
  test_dbt_snowflake:
    +materialized: table
    +generate_database_name: "{{ generate_database_name }}"

    ventas:
      staging:
        +schema: staging
        +materialized: table
      silver:
        +schema: silver
        +materialized: table
      gold:
        +schema: gold
        +materialized: table

    clientes:
      staging:
        +schema: staging
        +materialized: table
      gold:
        +schema: gold
        +materialized: table

    stock:
      staging:
        +schema: staging
        +materialized: table
      silver:
        +schema: silver
        +materialized: table

    supply:
      staging:
        +schema: staging
        +materialized: table
      silver:
        +schema: silver
        +materialized: table

    finanzas:
      staging:
        +schema: staging
        +materialized: table
      gold:
        +schema: gold
        +materialized: table

    comercial:
      silver:
        +schema: silver
        +materialized: table

    mkt:
      gold:
        +schema: gold
        +materialized: table
