name: 'test_dbt_snowflake'   # Nombre del proyecto
version: '1.0.0'             # Versión del proyecto

profile: 'test_dbt_snowflake'  # Nombre del profile a usar desde ~/.dbt/profiles.yml

# Rutas estándar para que dbt encuentre tus archivos
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Carpetas que se limpian con dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración por defecto para modelos
models:
  test_dbt_snowflake:

    # Capa de staging
    staging:
      +materialized: table      # ⬅️ por defecto crea tabla
      +schema: staging          # ⬅️ esquema donde se crean las tablas de staging

    # Capa silver
    silver:
      +materialized: table
      +schema: silver

    # Capa gold
    gold:
      +materialized: table
      +schema: gold

    # Puedes añadir más dominios si quieres separar por temas
    # ventas:
    #   +materialized: table
    #   +schema: gold_ventas

# Variables globales para usar en tus macros si necesitas
# vars:
#   my_var: "valor"
