version: 2

models:
  - name: stg_customers
    description: "Clientes de TPCH limpiados"
    columns:
      - name: customer_id
        description: "ID del cliente"
        tests:
          - not_null
          - unique
      - name: customer_name
        description: "Nombre del cliente"

