version: 2

models:
  - name: stg_customers
    description: "Clientes limpias de TPCH"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
  - name: stg_orders
    description: "Órdenes limpias de TPCH"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
