name: dbt CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala dbt + adaptador Snowflake
        run: pip install dbt-snowflake

      - name: Configura profile con secreto
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Instala dependencias dbt
        run: dbt deps

      - name: Ejecuta dbt build (run + test + snapshots)
        run: dbt build

      - name: Genera documentación dbt
        run: dbt docs generate

      - name: Publicar dbt docs en GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r target/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git add .
          git commit -m "Actualizar documentación dbt 🚀"
          git push origin gh-pages
